title: GNOME Türkiye
author: GNOME Türkiye Takımı
email: takim@gnome.org.tr
url: https://www.gnome.org.tr
baseurl: "/"
description: >
  GNOME masaüstü ortamı ve geliştirme platformu Türkiye resmi web sitesi.

permalink: /:slug.html

favicon: "logo.png"

remote_theme: riggraz/no-style-please

theme_config:
  #appearance: "dark"
  back_home_text: "GNOME Türkiye"
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
